# Generated by Django 4.2.5 on 2023-09-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_rename_name_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonview',
            name='last_view_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
